import { INodeProperties } from 'n8n-workflow';

export const contactOperations: INodeProperties[] = [
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: {
      show: { resource: ['contact'] },
    },
    options: [
      { name: 'Create', value: 'create', action: 'Create a contact' },
      { name: 'Delete', value: 'delete', action: 'Delete a contact' },
      { name: 'Get', value: 'get', action: 'Get a contact' },
      { name: 'Get Many', value: 'getAll', action: 'Get many contacts' },
      { name: 'Update', value: 'update', action: 'Update a contact' },
    ],
    default: 'getAll',
  },
];

export const contactFields: INodeProperties[] = [
  {
    displayName: 'Contact ID',
    name: 'contactId',
    type: 'string',
    required: true,
    displayOptions: {
      show: {
        resource: ['contact'],
        operation: ['get', 'update', 'delete'],
      },
    },
    default: '',
    description: 'The ID of the contact',
  },
  {
    displayName: 'Return All',
    name: 'returnAll',
    type: 'boolean',
    displayOptions: {
      show: {
        resource: ['contact'],
        operation: ['getAll'],
      },
    },
    default: false,
    description: 'Whether to return all results or only up to a given limit',
  },
  {
    displayName: 'Limit',
    name: 'limit',
    type: 'number',
    displayOptions: {
      show: {
        resource: ['contact'],
        operation: ['getAll'],
        returnAll: [false],
      },
    },
    typeOptions: {
      minValue: 1,
      maxValue: 100,
    },
    default: 50,
    description: 'Max number of results to return',
  },
  {
    displayName: 'First Name',
    name: 'first_name',
    type: 'string',
    required: true,
    displayOptions: {
      show: {
        resource: ['contact'],
        operation: ['create'],
      },
    },
    default: '',
    description: 'The first name of the contact',
  },
  {
    displayName: 'Last Name',
    name: 'last_name',
    type: 'string',
    required: true,
    displayOptions: {
      show: {
        resource: ['contact'],
        operation: ['create'],
      },
    },
    default: '',
    description: 'The last name of the contact',
  },
  {
    displayName: 'Additional Fields',
    name: 'additionalFields',
    type: 'collection',
    placeholder: 'Add Field',
    default: {},
    displayOptions: {
      show: {
        resource: ['contact'],
        operation: ['create', 'update'],
      },
    },
    options: [
      {
        displayName: 'Email',
        name: 'email',
        type: 'string',
        placeholder: 'name@example.com',
        default: '',
        description: 'Email address',
      },
      {
        displayName: 'Organization',
        name: 'organization',
        type: 'string',
        default: '',
        description: 'Organization name',
      },
      {
        displayName: 'Title',
        name: 'title',
        type: 'string',
        default: '',
        description: 'Job title',
      },
      {
        displayName: 'Mobile Phone',
        name: 'mobile_phone',
        type: 'string',
        default: '',
        description: 'Mobile phone number',
      },
      {
        displayName: 'Work Phone',
        name: 'work_phone',
        type: 'string',
        default: '',
        description: 'Work phone number',
      },
      {
        displayName: 'Website',
        name: 'website',
        type: 'string',
        default: '',
        description: 'Website URL',
      },
      {
        displayName: 'Billing Address',
        name: 'billing_address',
        type: 'string',
        default: '',
        description: 'Billing street address',
      },
      {
        displayName: 'Billing City',
        name: 'billing_city',
        type: 'string',
        default: '',
        description: 'Billing city',
      },
      {
        displayName: 'Billing Country ISO',
        name: 'billing_country_iso',
        type: 'string',
        default: '',
        description: 'Billing country ISO code (e.g., US, CA)',
      },
      {
        displayName: 'Billing Region ISO',
        name: 'billing_region_iso',
        type: 'string',
        default: '',
        description: 'Billing region/state ISO code',
      },
      {
        displayName: 'Billing Postal Code',
        name: 'billing_postal_code',
        type: 'string',
        default: '',
        description: 'Billing postal/zip code',
      },
      {
        displayName: 'Shipping Address',
        name: 'shipping_address',
        type: 'string',
        default: '',
        description: 'Shipping street address',
      },
      {
        displayName: 'Shipping City',
        name: 'shipping_city',
        type: 'string',
        default: '',
        description: 'Shipping city',
      },
      {
        displayName: 'Shipping Country ISO',
        name: 'shipping_country_iso',
        type: 'string',
        default: '',
        description: 'Shipping country ISO code',
      },
      {
        displayName: 'Shipping Region ISO',
        name: 'shipping_region_iso',
        type: 'string',
        default: '',
        description: 'Shipping region/state ISO code',
      },
      {
        displayName: 'Shipping Postal Code',
        name: 'shipping_postal_code',
        type: 'string',
        default: '',
        description: 'Shipping postal/zip code',
      },
      {
        displayName: 'SP Contact ID',
        name: 'sp_contact_id',
        type: 'string',
        default: '',
        description: 'Service provider contact ID',
      },
    ],
  },
  {
    displayName: 'Filters',
    name: 'filters',
    type: 'collection',
    placeholder: 'Add Filter',
    default: {},
    displayOptions: {
      show: {
        resource: ['contact'],
        operation: ['getAll'],
      },
    },
    options: [
      {
        displayName: 'First Name Contains',
        name: 'firstNameContains',
        type: 'string',
        default: '',
        description: 'Filter contacts where first name contains this value',
      },
      {
        displayName: 'Last Name Contains',
        name: 'lastNameContains',
        type: 'string',
        default: '',
        description: 'Filter contacts where last name contains this value',
      },
      {
        displayName: 'Email Contains',
        name: 'emailContains',
        type: 'string',
        default: '',
        description: 'Filter contacts where email contains this value',
      },
      {
        displayName: 'Organization Contains',
        name: 'organizationContains',
        type: 'string',
        default: '',
        description: 'Filter contacts where organization contains this value',
      },
      {
        displayName: 'Phone Contains',
        name: 'phoneContains',
        type: 'string',
        default: '',
        description: 'Filter contacts where phone contains this value',
      },
      {
        displayName: 'City Contains',
        name: 'cityContains',
        type: 'string',
        default: '',
        description: 'Filter contacts where city contains this value',
      },
      {
        displayName: 'Country',
        name: 'country',
        type: 'string',
        default: '',
        description: 'Filter by country ISO code',
      },
      {
        displayName: 'SP Contact ID',
        name: 'spContactId',
        type: 'string',
        default: '',
        description: 'Filter by service provider contact ID',
      },
      {
        displayName: 'Created After',
        name: 'createdAfter',
        type: 'dateTime',
        default: '',
        description: 'Filter contacts created after this date',
      },
      {
        displayName: 'Modified After',
        name: 'modifiedAfter',
        type: 'dateTime',
        default: '',
        description: 'Filter contacts modified after this date',
      },
    ],
  },
  {
    displayName: 'Options',
    name: 'options',
    type: 'collection',
    placeholder: 'Add Option',
    default: {},
    displayOptions: {
      show: {
        resource: ['contact'],
        operation: ['get', 'getAll', 'create', 'update'],
      },
    },
    options: [
      {
        displayName: 'Fields',
        name: 'fields',
        type: 'multiOptions',
        options: [
          { name: 'Billing Address', value: 'billing_address' },
          { name: 'Billing City', value: 'billing_city' },
          { name: 'Billing Country ISO', value: 'billing_country_iso' },
          { name: 'Billing Postal Code', value: 'billing_postal_code' },
          { name: 'Billing Region ISO', value: 'billing_region_iso' },
          { name: 'Created At', value: 'created_at' },
          { name: 'Email', value: 'email' },
          { name: 'First Name', value: 'first_name' },
          { name: 'ID', value: 'id' },
          { name: 'Last Name', value: 'last_name' },
          { name: 'Mobile Phone', value: 'mobile_phone' },
          { name: 'Modified At', value: 'modified_at' },
          { name: 'Organization', value: 'organization' },
          { name: 'Shipping Address', value: 'shipping_address' },
          { name: 'Shipping City', value: 'shipping_city' },
          { name: 'Shipping Country ISO', value: 'shipping_country_iso' },
          { name: 'Shipping Postal Code', value: 'shipping_postal_code' },
          { name: 'Shipping Region ISO', value: 'shipping_region_iso' },
          { name: 'Title', value: 'title' },
          { name: 'Website', value: 'website' },
          { name: 'Work Phone', value: 'work_phone' },
        ],
        default: [],
        description: 'Fields to include in the response',
      },
      {
        displayName: 'Sort By',
        name: 'sortBy',
        type: 'options',
        options: [
          { name: 'Created At (Asc)', value: '+created_at' },
          { name: 'Created At (Desc)', value: '-created_at' },
          { name: 'First Name (Asc)', value: '+first_name' },
          { name: 'First Name (Desc)', value: '-first_name' },
          { name: 'Last Name (Asc)', value: '+last_name' },
          { name: 'Last Name (Desc)', value: '-last_name' },
          { name: 'Email (Asc)', value: '+email' },
          { name: 'Email (Desc)', value: '-email' },
        ],
        default: '',
        description: 'Sort results by this field',
      },
    ],
  },
];

export const contactDescription = [...contactOperations, ...contactFields];
