import { INodeProperties } from 'n8n-workflow';

export const itemOperations: INodeProperties[] = [
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: {
      show: { resource: ['item'] },
    },
    options: [
      { name: 'Create', value: 'create', action: 'Create an item' },
      { name: 'Delete', value: 'delete', action: 'Delete an item' },
      { name: 'Get', value: 'get', action: 'Get an item' },
      { name: 'Get Many', value: 'getAll', action: 'Get many items' },
      { name: 'Update', value: 'update', action: 'Update an item' },
    ],
    default: 'getAll',
  },
];

export const itemFields: INodeProperties[] = [
  {
    displayName: 'Item ID',
    name: 'itemId',
    type: 'string',
    required: true,
    displayOptions: {
      show: {
        resource: ['item'],
        operation: ['get', 'update', 'delete'],
      },
    },
    default: '',
    description: 'The ID of the item',
  },
  {
    displayName: 'Return All',
    name: 'returnAll',
    type: 'boolean',
    displayOptions: {
      show: {
        resource: ['item'],
        operation: ['getAll'],
      },
    },
    default: false,
    description: 'Whether to return all results or only up to a given limit',
  },
  {
    displayName: 'Limit',
    name: 'limit',
    type: 'number',
    displayOptions: {
      show: {
        resource: ['item'],
        operation: ['getAll'],
        returnAll: [false],
      },
    },
    typeOptions: {
      minValue: 1,
      maxValue: 100,
    },
    default: 50,
    description: 'Max number of results to return',
  },
  {
    displayName: 'Name',
    name: 'name',
    type: 'string',
    required: true,
    displayOptions: {
      show: {
        resource: ['item'],
        operation: ['create'],
      },
    },
    default: '',
    description: 'The name of the item',
  },
  {
    displayName: 'Additional Fields',
    name: 'additionalFields',
    type: 'collection',
    placeholder: 'Add Field',
    default: {},
    displayOptions: {
      show: {
        resource: ['item'],
        operation: ['create', 'update'],
      },
    },
    options: [
      {
        displayName: 'Code (MPN)',
        name: 'code',
        type: 'string',
        default: '',
        description: 'Manufacturer part number',
      },
      {
        displayName: 'SKU',
        name: 'sku',
        type: 'string',
        default: '',
        description: 'Stock keeping unit',
      },
      {
        displayName: 'Description',
        name: 'description',
        type: 'string',
        typeOptions: {
          rows: 4,
        },
        default: '',
        description: 'Item description',
      },
      {
        displayName: 'Internal Note',
        name: 'internal_note',
        type: 'string',
        typeOptions: {
          rows: 4,
        },
        default: '',
        description: 'Internal notes (not visible to customers)',
      },
      {
        displayName: 'Category ID',
        name: 'category_id',
        type: 'string',
        default: '',
        description: 'ID of the category',
      },
      {
        displayName: 'Manufacturer ID',
        name: 'manufacturer_id',
        type: 'string',
        default: '',
        description: 'ID of the manufacturer',
      },
      {
        displayName: 'Supplier ID',
        name: 'supplier_id',
        type: 'string',
        default: '',
        description: 'ID of the supplier',
      },
      {
        displayName: 'Price (Decimal)',
        name: 'price_decimal',
        type: 'number',
        typeOptions: {
          numberPrecision: 2,
        },
        default: 0,
        description: 'Price as decimal number',
      },
      {
        displayName: 'Cost (Decimal)',
        name: 'cost_decimal',
        type: 'number',
        typeOptions: {
          numberPrecision: 2,
        },
        default: 0,
        description: 'Cost as decimal number',
      },
      {
        displayName: 'Cost Type',
        name: 'cost_type',
        type: 'options',
        options: [
          { name: 'Amount', value: 'amount' },
          { name: 'Percentage', value: 'percentage' },
        ],
        default: 'amount',
        description: 'Whether cost is an amount or percentage',
      },
      {
        displayName: 'Pricing Scheme',
        name: 'pricing_scheme',
        type: 'options',
        options: [
          { name: 'Per Unit', value: 'per_unit' },
          { name: 'Flat', value: 'flat' },
          { name: 'Tiered Volume', value: 'tiered_volume' },
          { name: 'Tiered Stepped', value: 'tiered_stepped' },
          { name: 'Percentage', value: 'percentage' },
        ],
        default: 'per_unit',
        description: 'Pricing scheme type',
      },
      {
        displayName: 'Taxable',
        name: 'taxable',
        type: 'boolean',
        default: false,
        description: 'Whether the item is taxable',
      },
      {
        displayName: 'Recurring',
        name: 'recurring',
        type: 'boolean',
        default: false,
        description: 'Whether the item is recurring',
      },
      {
        displayName: 'Recurring Interval',
        name: 'recurring_interval',
        type: 'options',
        options: [
          { name: 'Monthly', value: 'monthly' },
          { name: 'Quarterly', value: 'quarterly' },
          { name: 'Semi-Annually', value: 'semi_annually' },
          { name: 'Annually', value: 'annually' },
        ],
        default: 'monthly',
        description: 'Recurring interval (if recurring is true)',
        displayOptions: {
          show: {
            '/resource': ['item'],
            '/operation': ['create', 'update'],
          },
        },
      },
      {
        displayName: 'Weight (Decimal)',
        name: 'weight_decimal',
        type: 'number',
        typeOptions: {
          numberPrecision: 2,
        },
        default: 0,
        description: 'Weight as decimal number',
      },
      {
        displayName: 'Allow Decimal Quantities',
        name: 'allow_decimal_quantities',
        type: 'boolean',
        default: false,
        description: 'Whether to allow decimal quantities',
      },
      {
        displayName: 'Restrict Discounting',
        name: 'restrict_discounting',
        type: 'boolean',
        default: false,
        description: 'Whether to restrict discounting',
      },
      {
        displayName: 'Show Option Prices',
        name: 'show_option_prices',
        type: 'boolean',
        default: false,
        description: 'Whether to show option prices',
      },
      {
        displayName: 'Quantity Help Tip',
        name: 'quantity_help_tip',
        type: 'string',
        default: '',
        description: 'Help text for quantity field',
      },
      {
        displayName: 'Percentage Price (Decimal)',
        name: 'percentage_price_decimal',
        type: 'number',
        typeOptions: {
          numberPrecision: 2,
        },
        default: 0,
        description: 'Percentage price as decimal (for percentage pricing scheme)',
      },
      {
        displayName: 'Percentage Price Category IDs',
        name: 'percentage_price_category_ids',
        type: 'string',
        default: '',
        description: 'Comma-separated category IDs for percentage pricing',
      },
    ],
  },
  {
    displayName: 'Filters',
    name: 'filters',
    type: 'collection',
    placeholder: 'Add Filter',
    default: {},
    displayOptions: {
      show: {
        resource: ['item'],
        operation: ['getAll'],
      },
    },
    options: [
      {
        displayName: 'Name Contains',
        name: 'nameContains',
        type: 'string',
        default: '',
        description: 'Filter items where name contains this value',
      },
      {
        displayName: 'Code Contains',
        name: 'codeContains',
        type: 'string',
        default: '',
        description: 'Filter items where code contains this value',
      },
      {
        displayName: 'SKU Contains',
        name: 'skuContains',
        type: 'string',
        default: '',
        description: 'Filter items where SKU contains this value',
      },
      {
        displayName: 'Category ID',
        name: 'categoryId',
        type: 'string',
        default: '',
        description: 'Filter by category ID',
      },
      {
        displayName: 'Manufacturer ID',
        name: 'manufacturerId',
        type: 'string',
        default: '',
        description: 'Filter by manufacturer ID',
      },
      {
        displayName: 'Supplier ID',
        name: 'supplierId',
        type: 'string',
        default: '',
        description: 'Filter by supplier ID',
      },
      {
        displayName: 'Created After',
        name: 'createdAfter',
        type: 'dateTime',
        default: '',
        description: 'Filter items created after this date',
      },
      {
        displayName: 'Modified After',
        name: 'modifiedAfter',
        type: 'dateTime',
        default: '',
        description: 'Filter items modified after this date',
      },
    ],
  },
  {
    displayName: 'Options',
    name: 'options',
    type: 'collection',
    placeholder: 'Add Option',
    default: {},
    displayOptions: {
      show: {
        resource: ['item'],
        operation: ['get', 'getAll', 'create', 'update'],
      },
    },
    options: [
      {
        displayName: 'Fields',
        name: 'fields',
        type: 'multiOptions',
        options: [
          { name: 'Allow Decimal Quantities', value: 'allow_decimal_quantities' },
          { name: 'Category', value: 'category' },
          { name: 'Category ID', value: 'category_id' },
          { name: 'Code', value: 'code' },
          { name: 'Cost Decimal', value: 'cost_decimal' },
          { name: 'Cost Type', value: 'cost_type' },
          { name: 'Created At', value: 'created_at' },
          { name: 'Description', value: 'description' },
          { name: 'ID', value: 'id' },
          { name: 'Internal Note', value: 'internal_note' },
          { name: 'Manufacturer', value: 'manufacturer' },
          { name: 'Manufacturer ID', value: 'manufacturer_id' },
          { name: 'Modified At', value: 'modified_at' },
          { name: 'Name', value: 'name' },
          { name: 'Percentage Price Category IDs', value: 'percentage_price_category_ids' },
          { name: 'Percentage Price Decimal', value: 'percentage_price_decimal' },
          { name: 'Price Decimal', value: 'price_decimal' },
          { name: 'Pricing Scheme', value: 'pricing_scheme' },
          { name: 'Quantity Help Tip', value: 'quantity_help_tip' },
          { name: 'Recurring', value: 'recurring' },
          { name: 'Recurring Interval', value: 'recurring_interval' },
          { name: 'Restrict Discounting', value: 'restrict_discounting' },
          { name: 'Show Option Prices', value: 'show_option_prices' },
          { name: 'SKU', value: 'sku' },
          { name: 'Supplier', value: 'supplier' },
          { name: 'Supplier ID', value: 'supplier_id' },
          { name: 'Taxable', value: 'taxable' },
          { name: 'Weight Decimal', value: 'weight_decimal' },
        ],
        default: [],
        description: 'Fields to include in the response',
      },
      {
        displayName: 'Sort By',
        name: 'sortBy',
        type: 'options',
        options: [
          { name: 'Created At (Asc)', value: '+created_at' },
          { name: 'Created At (Desc)', value: '-created_at' },
          { name: 'Name (Asc)', value: '+name' },
          { name: 'Name (Desc)', value: '-name' },
          { name: 'Code (Asc)', value: '+code' },
          { name: 'Code (Desc)', value: '-code' },
        ],
        default: '',
        description: 'Sort results by this field',
      },
    ],
  },
];

export const itemDescription = [...itemOperations, ...itemFields];
