import { INodeProperties } from 'n8n-workflow';

export const quoteOperations: INodeProperties[] = [
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: {
      show: { resource: ['quote'] },
    },
    options: [
      { name: 'Create', value: 'create', action: 'Create a quote' },
      { name: 'Delete', value: 'delete', action: 'Delete a quote' },
      { name: 'Get', value: 'get', action: 'Get a quote' },
      { name: 'Get Many', value: 'getAll', action: 'Get many quotes' },
      { name: 'Update', value: 'update', action: 'Update a quote' },
    ],
    default: 'getAll',
  },
];

export const quoteFields: INodeProperties[] = [
  {
    displayName: 'Quote ID',
    name: 'quoteId',
    type: 'string',
    required: true,
    displayOptions: {
      show: {
        resource: ['quote'],
        operation: ['get', 'update', 'delete'],
      },
    },
    default: '',
    description: 'The ID of the quote',
  },
  {
    displayName: 'Return All',
    name: 'returnAll',
    type: 'boolean',
    displayOptions: {
      show: {
        resource: ['quote'],
        operation: ['getAll'],
      },
    },
    default: false,
    description: 'Whether to return all results or only up to a given limit',
  },
  {
    displayName: 'Limit',
    name: 'limit',
    type: 'number',
    displayOptions: {
      show: {
        resource: ['quote'],
        operation: ['getAll'],
        returnAll: [false],
      },
    },
    typeOptions: {
      minValue: 1,
      maxValue: 100,
    },
    default: 50,
    description: 'Max number of results to return',
  },
  {
    displayName: 'Template ID',
    name: 'template_id',
    type: 'string',
    required: true,
    displayOptions: {
      show: {
        resource: ['quote'],
        operation: ['create'],
      },
    },
    default: '',
    description: 'The ID of the quote template',
  },
  {
    displayName: 'Contact ID',
    name: 'contact_id',
    type: 'string',
    required: true,
    displayOptions: {
      show: {
        resource: ['quote'],
        operation: ['create'],
      },
    },
    default: '',
    description: 'The ID of the contact',
  },
  {
    displayName: 'Additional Fields',
    name: 'additionalFields',
    type: 'collection',
    placeholder: 'Add Field',
    default: {},
    displayOptions: {
      show: {
        resource: ['quote'],
        operation: ['create', 'update'],
      },
    },
    options: [
      {
        displayName: 'Name',
        name: 'name',
        type: 'string',
        default: '',
        description: 'Quote name',
      },
      {
        displayName: 'Custom Number',
        name: 'custom_number',
        type: 'string',
        default: '',
        description: 'Custom quote number',
      },
      {
        displayName: 'Status',
        name: 'status',
        type: 'options',
        options: [
          { name: 'Pending', value: 'pending' },
          { name: 'Sent', value: 'sent' },
          { name: 'Won', value: 'won' },
          { name: 'Lost', value: 'lost' },
        ],
        default: 'pending',
        description: 'Quote status',
      },
      {
        displayName: 'Draft',
        name: 'draft',
        type: 'boolean',
        default: false,
        description: 'Whether the quote is a draft',
      },
      {
        displayName: 'Flagged',
        name: 'flagged',
        type: 'boolean',
        default: false,
        description: 'Whether the quote is flagged',
      },
      {
        displayName: 'Owner ID',
        name: 'owner_id',
        type: 'string',
        default: '',
        description: 'ID of the quote owner',
      },
      {
        displayName: 'Currency ISO',
        name: 'currency_iso',
        type: 'string',
        default: 'USD',
        description: 'Currency ISO code (e.g., USD, EUR)',
      },
      {
        displayName: 'Expired At',
        name: 'expired_at',
        type: 'dateTime',
        default: '',
        description: 'Expiration date and time',
      },
      {
        displayName: 'Internal Notes',
        name: 'internal_notes',
        type: 'string',
        typeOptions: {
          rows: 4,
        },
        default: '',
        description: 'Internal notes',
      },
      {
        displayName: 'Billing Address',
        name: 'billing_address',
        type: 'string',
        default: '',
        description: 'Billing street address',
      },
      {
        displayName: 'Billing City',
        name: 'billing_city',
        type: 'string',
        default: '',
        description: 'Billing city',
      },
      {
        displayName: 'Billing Country ISO',
        name: 'billing_country_iso',
        type: 'string',
        default: '',
        description: 'Billing country ISO code',
      },
      {
        displayName: 'Billing Region ISO',
        name: 'billing_region_iso',
        type: 'string',
        default: '',
        description: 'Billing region/state ISO code',
      },
      {
        displayName: 'Billing Postal Code',
        name: 'billing_postal_code',
        type: 'string',
        default: '',
        description: 'Billing postal/zip code',
      },
      {
        displayName: 'Shipping Address',
        name: 'shipping_address',
        type: 'string',
        default: '',
        description: 'Shipping street address',
      },
      {
        displayName: 'Shipping City',
        name: 'shipping_city',
        type: 'string',
        default: '',
        description: 'Shipping city',
      },
      {
        displayName: 'Shipping Country ISO',
        name: 'shipping_country_iso',
        type: 'string',
        default: '',
        description: 'Shipping country ISO code',
      },
      {
        displayName: 'Shipping Region ISO',
        name: 'shipping_region_iso',
        type: 'string',
        default: '',
        description: 'Shipping region/state ISO code',
      },
      {
        displayName: 'Shipping Postal Code',
        name: 'shipping_postal_code',
        type: 'string',
        default: '',
        description: 'Shipping postal/zip code',
      },
      {
        displayName: 'Shipping (Decimal)',
        name: 'shipping_decimal',
        type: 'number',
        typeOptions: {
          numberPrecision: 2,
        },
        default: 0,
        description: 'Shipping cost as decimal',
      },
      {
        displayName: 'SP Client ID',
        name: 'sp_client_id',
        type: 'string',
        default: '',
        description: 'Service provider client ID',
      },
    ],
  },
  {
    displayName: 'Filters',
    name: 'filters',
    type: 'collection',
    placeholder: 'Add Filter',
    default: {},
    displayOptions: {
      show: {
        resource: ['quote'],
        operation: ['getAll'],
      },
    },
    options: [
      {
        displayName: 'ID',
        name: 'id',
        type: 'string',
        default: '',
        description: 'Filter by quote ID',
      },
      {
        displayName: 'Name Contains',
        name: 'nameContains',
        type: 'string',
        default: '',
        description: 'Filter quotes where name contains this value',
      },
      {
        displayName: 'Custom Number',
        name: 'customNumber',
        type: 'string',
        default: '',
        description: 'Filter by custom number',
      },
      {
        displayName: 'UUID',
        name: 'uuid',
        type: 'string',
        default: '',
        description: 'Filter by UUID',
      },
      {
        displayName: 'Status',
        name: 'status',
        type: 'options',
        options: [
          { name: 'Pending', value: 'pending' },
          { name: 'Sent', value: 'sent' },
          { name: 'Won', value: 'won' },
          { name: 'Lost', value: 'lost' },
        ],
        default: '',
        description: 'Filter by status',
      },
      {
        displayName: 'Draft',
        name: 'draft',
        type: 'boolean',
        default: false,
        description: 'Filter by draft status',
      },
      {
        displayName: 'Email Status',
        name: 'emailStatus',
        type: 'string',
        default: '',
        description: 'Filter by email status',
      },
      {
        displayName: 'Recurring Interval',
        name: 'recurringInterval',
        type: 'options',
        options: [
          { name: 'Monthly', value: 'monthly' },
          { name: 'Quarterly', value: 'quarterly' },
          { name: 'Semi-Annually', value: 'semi_annually' },
          { name: 'Annually', value: 'annually' },
        ],
        default: '',
        description: 'Filter by recurring interval',
      },
      {
        displayName: 'SP Client ID',
        name: 'spClientId',
        type: 'string',
        default: '',
        description: 'Filter by service provider client ID',
      },
      {
        displayName: 'Created After',
        name: 'createdAfter',
        type: 'dateTime',
        default: '',
        description: 'Filter quotes created after this date',
      },
      {
        displayName: 'Modified After',
        name: 'modifiedAfter',
        type: 'dateTime',
        default: '',
        description: 'Filter quotes modified after this date',
      },
      {
        displayName: 'Expired After',
        name: 'expiredAfter',
        type: 'dateTime',
        default: '',
        description: 'Filter quotes expired after this date',
      },
      {
        displayName: 'Won After',
        name: 'wonAfter',
        type: 'dateTime',
        default: '',
        description: 'Filter quotes won after this date',
      },
    ],
  },
  {
    displayName: 'Options',
    name: 'options',
    type: 'collection',
    placeholder: 'Add Option',
    default: {},
    displayOptions: {
      show: {
        resource: ['quote'],
        operation: ['get', 'getAll', 'create', 'update'],
      },
    },
    options: [
      {
        displayName: 'Fields',
        name: 'fields',
        type: 'multiOptions',
        options: [
          { name: 'Annual Cost', value: 'annual_cost' },
          { name: 'Annual Discount', value: 'annual_discount' },
          { name: 'Annual Margin', value: 'annual_margin' },
          { name: 'Annual Subtotal', value: 'annual_subtotal' },
          { name: 'Annual Tax Total', value: 'annual_tax_total' },
          { name: 'Annual Total', value: 'annual_total' },
          { name: 'Billing Address', value: 'billing_address' },
          { name: 'Billing City', value: 'billing_city' },
          { name: 'Billing Country ISO', value: 'billing_country_iso' },
          { name: 'Billing Postal Code', value: 'billing_postal_code' },
          { name: 'Billing Region ISO', value: 'billing_region_iso' },
          { name: 'Contact', value: 'contact' },
          { name: 'Contact ID', value: 'contact_id' },
          { name: 'Created At', value: 'created_at' },
          { name: 'Currency ISO', value: 'currency_iso' },
          { name: 'Custom Number', value: 'custom_number' },
          { name: 'Draft', value: 'draft' },
          { name: 'Email First Sent At', value: 'email_first_sent_at' },
          { name: 'Email Last Sent At', value: 'email_last_sent_at' },
          { name: 'Email Status', value: 'email_status' },
          { name: 'Expired At', value: 'expired_at' },
          { name: 'Flagged', value: 'flagged' },
          { name: 'ID', value: 'id' },
          { name: 'Internal Notes', value: 'internal_notes' },
          { name: 'Modified At', value: 'modified_at' },
          { name: 'Monthly Cost', value: 'monthly_cost' },
          { name: 'Monthly Discount', value: 'monthly_discount' },
          { name: 'Monthly Margin', value: 'monthly_margin' },
          { name: 'Monthly Subtotal', value: 'monthly_subtotal' },
          { name: 'Monthly Tax Total', value: 'monthly_tax_total' },
          { name: 'Monthly Total', value: 'monthly_total' },
          { name: 'Name', value: 'name' },
          { name: 'Number', value: 'number' },
          { name: 'One Time Cost', value: 'one_time_cost' },
          { name: 'One Time Discount', value: 'one_time_discount' },
          { name: 'One Time Margin', value: 'one_time_margin' },
          { name: 'One Time Subtotal', value: 'one_time_subtotal' },
          { name: 'One Time Tax Total', value: 'one_time_tax_total' },
          { name: 'One Time Total', value: 'one_time_total' },
          { name: 'Owner', value: 'owner' },
          { name: 'Owner ID', value: 'owner_id' },
          { name: 'Quarterly Cost', value: 'quarterly_cost' },
          { name: 'Quarterly Discount', value: 'quarterly_discount' },
          { name: 'Quarterly Margin', value: 'quarterly_margin' },
          { name: 'Quarterly Subtotal', value: 'quarterly_subtotal' },
          { name: 'Quarterly Tax Total', value: 'quarterly_tax_total' },
          { name: 'Quarterly Total', value: 'quarterly_total' },
          { name: 'Revision', value: 'revision' },
          { name: 'Semi Annual Cost', value: 'semi_annual_cost' },
          { name: 'Semi Annual Discount', value: 'semi_annual_discount' },
          { name: 'Semi Annual Margin', value: 'semi_annual_margin' },
          { name: 'Semi Annual Subtotal', value: 'semi_annual_subtotal' },
          { name: 'Semi Annual Tax Total', value: 'semi_annual_tax_total' },
          { name: 'Semi Annual Total', value: 'semi_annual_total' },
          { name: 'Shipping Address', value: 'shipping_address' },
          { name: 'Shipping City', value: 'shipping_city' },
          { name: 'Shipping Country ISO', value: 'shipping_country_iso' },
          { name: 'Shipping Decimal', value: 'shipping_decimal' },
          { name: 'Shipping Postal Code', value: 'shipping_postal_code' },
          { name: 'Shipping Region ISO', value: 'shipping_region_iso' },
          { name: 'Status', value: 'status' },
          { name: 'UUID', value: 'uuid' },
          { name: 'Won At', value: 'won_at' },
        ],
        default: [],
        description: 'Fields to include in the response',
      },
      {
        displayName: 'Sort By',
        name: 'sortBy',
        type: 'options',
        options: [
          { name: 'Created At (Asc)', value: '+created_at' },
          { name: 'Created At (Desc)', value: '-created_at' },
          { name: 'Modified At (Asc)', value: '+modified_at' },
          { name: 'Modified At (Desc)', value: '-modified_at' },
          { name: 'Name (Asc)', value: '+name' },
          { name: 'Name (Desc)', value: '-name' },
          { name: 'Number (Asc)', value: '+number' },
          { name: 'Number (Desc)', value: '-number' },
        ],
        default: '',
        description: 'Sort results by this field',
      },
    ],
  },
];

export const quoteDescription = [...quoteOperations, ...quoteFields];
